<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TsvFunctions\Module'                        => __DIR__ . '/Module.php',
    'TsvFunctions\Controller\TsvFunctionsController' => __DIR__ . '/src/TsvFunctions/Controller/TsvFunctionsController.php',
    'TsvFunctionsTest\Framework\TestCase'        => __DIR__ . '/tests/TsvFunctions/Framework/TestCase.php',
    'TsvFunctionsTest\SampleTest'                => __DIR__ . '/tests/TsvFunctions/SampleTest.php',
);
